### ISSUE TITLE
Firefox issues

### ISSUE THREAD

**Issue by danvoyce** [noahblon/animated-climacons#1]
Animations aren't looking great in Firefox 26.

**Comment by FlorentBiffi** [comment]
I've the same problem, have you find a solution ?
(for the time being, I have deactivate the rotate animation)

**Comment by noahblon** [comment]
Hi all, unfortunately Firefox doesn't support the transform-origin property at this time, which means the origin of transforms such as rotate happen at the top left of the document.  It is possible to use a group to push the origin to the middle of the svg, then translate items inside so that their centers are the upper left of the group, a solution I've outlined in this demo:
http://codepen.io/noahblon/pen/DlvhJ
Potentially I could go through and rework these to include the hack, but I'd prefer to wait until transform-origin for SVG is properly supported in Firefox.
